version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/awana-app
      dockerfile: Dockerfile
    container_name: awana-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    networks:
      - awana-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: awana-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=awana
      - DB_PASSWORD=awana
      - DB_NAME=awana_db
      - DOCKER_ENV=true
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - awana-network

  mysql:
    image: mysql:8.0
    container_name: awana-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: awana_db
      MYSQL_USER: awana
      MYSQL_PASSWORD: awana
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3306", "-u", "awana", "-pawana"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - awana-network

networks:
  awana-network:
    driver: bridge

volumes:
  mysql_data:
