version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/awana-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - awana-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=awana_events
    depends_on:
      - mysql
    networks:
      - awana-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=awana_events
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - awana-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  awana-network:
    driver: bridge

volumes:
  mysql-data:
