version: '3.8'

services:
<<<<<<< HEAD
  frontend:
    build:
      context: ./frontend/awana-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
=======
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AWANAKOREA353
      MYSQL_DATABASE: test
      MYSQL_USER: awana
      MYSQL_PASSWORD: AWANAKOREA353
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: awana
      DB_PASSWORD: AWANAKOREA353
      DB_NAME: test
>>>>>>> f27e4e000d0e3df0a6edc54cc02fad4ad0906ce5
    ports:
      - "5000:5000"
    depends_on:
      - mysql
<<<<<<< HEAD
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=awana_events
    volumes:
      - ./backend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=awana_events
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
=======

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
>>>>>>> f27e4e000d0e3df0a6edc54cc02fad4ad0906ce5
