/*
-- Query: SELECT * FROM awana_db.sampleeventdb
LIMIT 0, 1000

-- Date: 2025-04-14 13:29
*/
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (1,'성경퀴즈대회','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','1월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (2,'YM Summit','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','1월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (3,'상반기 연합 BT','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','2월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (4,'컨퍼런스','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','3월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (5,'올림픽 설명회','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','4월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (6,'올림픽','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','5월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (7,'조정관 학교 101','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','6월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (8,'조정관 학교 201','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','6월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (9,'T&T Camp','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','7월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (10,'감독관 학교 101','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','8월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (11,'YM MIT','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','8월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (12,'하반기 연합 BT','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','9월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (13,'영성수련회','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','10월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (14,'성경퀴즈대회 설명회','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','11월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (15,'비전캠프','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','12월',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (16,'장학캠프','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','미정',NULL);
INSERT INTO `` (`event_ID`,`event_Name`,`event_Location`,`event_Year`,`event_Start_Date`,`event_End_Date`,`event_Registration_Start_Date`,`event_Registration_End_Date`,`event_Open_Available`,`event_Place`,`event_Month`,`event_Description`) VALUES (17,'수시 BT','미정','미정',NULL,NULL,NULL,NULL,'비공개','미정','미정',NULL);
